### ISSUE TITLE
Support for projects targeting JDK 1.7

### ISSUE THREAD

**Issue by dobridog** [launchdarkly/android-client#34]
Transitive dependency `com.google.guava:guava:XY.Z` on 'com.launchdarkly:launchdarkly-android-client:X.Y.Z` is causing compilation errors on project with compileOptions targeting javac 1.7. 

Options:
- Upgrade our project to javac 1.8 (not possible until gradle tools 3.1.0 is stable due to https://github.com/square/okio/issues/325)
- Launch Darkly use Android compatible Guava `XY.Z-android` dependency (https://github.com/google/guava#guava-google-core-libraries-for-java)

Workaround: 
```
compile ('com.launchdarkly:launchdarkly-android-client:2.1.0') {
        exclude group: 'com.google.guava', module: 'guava'
}
// swap LD guava dependency with an Android compatible one
compile 'com.google.guava:guava:22.0-android'
```

**Comment by byencho** [comment]
I have a similar problem, but it doesn't appear to be linked to Guava, so I don't have a workaround. The app I'm working on explicitly targets JDK 1.7 but LD itself (as of [2.1.0](https://github.com/launchdarkly/android-client/commit/b4ad5fdee0a34570a848358778bc93b546b3296b) clearly uses 1.8:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

I simply can't build with any LD versions that include this constraint.

**Comment by arun251** [comment]
This issue should be fixed in release 2.2.1, released today.
